import { notFound } from 'next/navigation'
import { LEAGUES } from '@/types'
import { getManagerProfile } from '@/lib/ai/manager-profile'
import { fetchStandings } from '@/lib/api-football/client'
import { PhilosophyCard } from '@/components/manager/PhilosophyCard'
import { CareerTimeline } from '@/components/manager/CareerTimeline'

interface Props {
  params: Promise<{ teamId: string }>
  searchParams: Promise<{ league?: string }>
}

export default async function ManagerPage({ params, searchParams }: Props) {
  const { teamId } = await params
  const { league: leagueSlug = 'premier-league' } = await searchParams

  const meta = LEAGUES.find(l => l.slug === leagueSlug)
  if (!meta) notFound()

  const id = parseInt(teamId, 10)
  if (isNaN(id)) notFound()

  let profile = null
  try {
    const standings = await fetchStandings(meta.apiId)
    const team = standings.find(s => s.team.id === id)
    const teamName = team?.team.name ?? `Team ${id}`
    profile = await getManagerProfile(id, teamName)
  } catch (err) {
    console.error('Manager profile error:', err)
  }

  if (!profile) {
    return (
      <div className="p-6 rounded-xl border border-yellow-900/40 bg-yellow-900/10 space-y-3">
        <p className="font-semibold text-yellow-400">🔑 Anthropic API key required</p>
        <p className="text-sm text-gray-400">
          The Manager DNA feature uses Claude AI to generate tactical analyses. To enable it:
        </p>
        <ol className="text-sm text-gray-400 space-y-1 list-decimal list-inside">
          <li>Go to <span className="text-[#00ff85]">console.anthropic.com</span> → API Keys → Create key</li>
          <li>In Vercel: Project → Settings → Environment Variables</li>
          <li>Add <code className="text-[#00ff85] bg-black/30 px-1 rounded">ANTHROPIC_API_KEY</code> = your key</li>
          <li>Redeploy the project</li>
        </ol>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold mb-1">Manager Philosophy</h2>
        <p className="text-sm text-gray-400">
          AI-powered tactical deep-dive based on publicly available football analysis.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
          <PhilosophyCard profile={profile} />
        </div>
        <div className="space-y-4">
          <CareerTimeline profile={profile} />
          {/* FPL implications */}
          <div className="p-4 rounded-xl border border-[#1e3329] bg-[#0f3d2e]/30">
            <h3 className="text-xs font-semibold text-[#00ff85] uppercase tracking-wider mb-2">FPL Insight</h3>
            <p className="text-sm text-gray-300">{profile.fplImplications}</p>
          </div>
          <p className="text-xs text-gray-500">
            Analysis generated by Claude AI · Last updated {new Date(profile.generatedAt).toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  )
}
